fixed initial state of gallery and buttons
FineUploader/react-fine-uploader pull request #134
Opened 2017-06-20 08:17 UTC by mladen107

I added initial state based on current state of uploader to galllery, cancel, delete and retry buttons. 

This should fix [#128](https://github.com/FineUploader/react-fine-uploader/issues/128). Also now it is possible to call `uploader.methods.addInitialFiles` before creating gallery and see initial files.

2017-07-15 14:33 UTC, pyaesone17 commented
I think I need deleteable button for initial files.

2017-10-04 04:28 UTC, rnicholus requested changes
Some good changes, but at least a couple should either be removed or fixed.

2017-10-04 04:28 UTC, rnicholus commented on src/cancel-button.jsx
> +        statusEnum.SUBMITTING,
Why was this added?

2017-10-04 04:28 UTC, rnicholus commented on src/filename.jsx
> +                  onClick={this._onClick}>
Why does the `<Filename>` component have a click handler? Furthermore, this is completely inaccessible.

2018-01-23 06:24 UTC, closed without merging