PR-134 Updates
FineUploader/react-fine-uploader pull request #155
Opened 2017-10-25 16:27 UTC by 5arias

Given that @mladen107 hasn't had the time to make the updates for his PR, I went ahead and made them since I need support for adding initial files in the gallery as well.

I removed the onClick functionality in src/filename.jsx for the time being. This is a feature that I'll be adding in for my project in the somewhat near future, however I believe it should include status checks, onClick and href support - features which I didn't have time to write last night.

I also rearranged the order of the isCancelable status array to reflect the status workflow detailed in the [stats & status documentation](https://docs.fineuploader.com/branch/master/features/statistics-and-status-updates.html)

To answer @rnicholus comment regarding the statusEnum.SUBMITTING status being included, I agree with @mladen107 that this status should be included because it describes a cancelable event (validation checks occur during this event).

2017-10-25 17:10 UTC, mladen107 commented
Sorry for not updating my PR. At the end, I needed much more complex UI so I wrote my own from scratch. I agree that onClick should be separate pull request.

2017-10-25 23:19 UTC, rnicholus requested changes
One change, and this really needs more tests, especially on the impacted components.

2017-10-25 23:19 UTC, rnicholus commented on src/gallery/index.jsx
> +            visibleFiles: props.uploader.methods.getUploads()
Let's limit each file entry to the `id` and optionally `fromServer`.

2017-10-26 16:00 UTC, 5arias commented on src/gallery/index.jsx
> +            visibleFiles: props.uploader.methods.getUploads()
Sounds good and I agree about the tests. I probably won't be able to get to it until next week. Thanks!

2017-10-26 16:00 UTC, 5arias commented
@mladen107 All good, I appreciate your initial work on it!

2017-11-08 15:05 UTC, 5arias commented
@rnicholus I refactored to limit the initial file objects to ID and Status. I haven't had the time to work on making `fromServer` optional. 

Also what other tests would you like to see?

2018-01-27 03:00 UTC, rnicholus commented
Can someone remind me what problem we are trying to solve here? Seems like a lot of changes as well...

2018-08-09 03:15 UTC, rnicholus commented
closing due to inactivity

2018-08-09 03:15 UTC, closed without merging