Azure Wrapper
FineUploader/react-fine-uploader pull request #54
Opened 2016-12-09 16:36 UTC by tgandrews

This seems to work for me and resolves issue #3

2016-12-09 16:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FineUploader/react-fine-uploader?pullRequest=54) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FineUploader/react-fine-uploader?pullRequest=54) before we can accept your contribution.<br/>

2016-12-09 16:46 UTC, rnicholus commented
Thanks! A few things before this can proceed:

- [ ] Documentation updates to the README.md file, similar to the S3 & Traditional sections.
- [ ] Can you post here specifics about your Azure setup, or at least your client-side code? I'm a bit more careful with Azure-related updates since I don't use Azure myself.
- [ ] We'll need to release a new version, but I'll take care of that myself last.

2016-12-09 16:50 UTC, tgandrews commented
RE: Documentation. Is it ok to add links to the core fine-uploader areas? I'll add my working example as well.

2016-12-09 16:56 UTC, rnicholus commented
Please do link to any areas that you feel are useful. But it should at least follow the same format & tone as the existing [S3](https://github.com/FineUploader/react-fine-uploader#s3) and [Traditional](https://github.com/FineUploader/react-fine-uploader#traditional) sections in the readme.

2016-12-10 08:17 UTC, tgandrews commented
Is this sufficient?

2016-12-10 21:47 UTC, rnicholus requested changes
Otherwise looks good to me. Are you already using these changes in your app?

2016-12-10 21:47 UTC, rnicholus commented on README.md
> +   - [Azure](#azure) - upload files directly to Azure storage
Can you move this to the 1st item (to maintain ABC ordering)?

2016-12-12 08:45 UTC, tgandrews commented
I've updated the order.

RE use: It's not fully integrated and in production yet. But, it works well in our PoC.

2016-12-12 16:30 UTC, rnicholus approved these changes

2016-12-12 16:32 UTC, rnicholus commented
I think this can go out at 0.3.0 since 0.x.x already let developers know that this library is not yet stable. Thanks for your work on this. Can you also add a link to the [Azure feature page](http://docs.fineuploader.com/branch/master/features/azure.html) in the docs, similar to what I have done with the S3 section?

2016-12-12 16:46 UTC, tgandrews commented
Updated the docs to include the azure feature page info and also included the server examples as well.

2016-12-12 16:56 UTC, rnicholus commented
Awesome! Are you interested in becoming a collaborator on this project?

2016-12-13 02:36 UTC, rnicholus commented on src/wrappers/azure.js
> +import { traditional as callbackNames } from './callback-names'
Oh! One thing missing here we need a set of "azure" callback names. I'll fix and merge.

2016-12-13 02:40 UTC, rnicholus commented on src/wrappers/azure.js
> +import { traditional as callbackNames } from './callback-names'
On second thought - that can wait until we actually _have_ some Azure-specific callbacks.

2016-12-13 02:42 UTC, merged

2016-12-13 09:49 UTC, tgandrews commented
Awesome :tada:

Thanks for merging. I'm happy to help where I can especially regarding azure specific things and I'll let you know if we have any issues in prod